# fly.toml app configuration file generated for jobbotv2 on 2026-08-13T08:56:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobbotv2'
primary_region = 'yyz'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[[mounts]]
  source = 'jobot_data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
