"""Voice playground (REQ-046, ADR-068) — tune the coach's voice by ear, -edu only.

Gemini has no pitch/rate/SSML knob on native audio. What really moves the
sound is: the voice (30 prebuilt), a natural-language DELIVERY line ("speak
slowly, calm…"), the personality, and — in Live only — the experimental
toggles (affective dialog, proactive audio) and turn-taking (VAD). This module
exposes exactly those knobs:

  - Takes: generated by the REAL Live model (same model/voice/config as the
    coach) — "script" (Live reads your line) or "opening" (Live improvises the
    real coach opening) — saved raw AND with Jobot's pause stretch applied.
  - Takes: every Play is recorded (config + line + WAV) in a side list where
    Eduardo replays, rates 1–5 and likes them to compare mixed settings —
    one JSON file on the volume (the lab never touches users' schemas).
  - Live override: a config saved here is applied to the REAL practice session
    (`live._config`) while the lab flag is on, so a full mini-interview can be
    heard with it. Off the flag → ignored.

Everything is gated by `JOBOT_VOICE_LAB=1` (set only on -edu). Winners are
promoted to `live.VOICES` / the P7 prompt by a normal code change + ADR — the
lab never changes what users get.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
from pathlib import Path
from typing import Any, Optional

from core import settings as app_settings

# The 30 Gemini prebuilt voices with Google's one-word character description.
# (Perceived gender is ours, for the picker only — Google doesn't label it.)
GEMINI_VOICES: dict[str, tuple[str, str]] = {
    "Achernar": ("Soft", "f"), "Achird": ("Friendly", "m"), "Algenib": ("Gravelly", "m"),
    "Algieba": ("Smooth", "m"), "Alnilam": ("Firm", "m"), "Aoede": ("Breezy", "f"),
    "Autonoe": ("Bright", "f"), "Callirrhoe": ("Easy-going", "f"), "Charon": ("Informative", "m"),
    "Despina": ("Smooth", "f"), "Enceladus": ("Breathy", "m"), "Erinome": ("Clear", "f"),
    "Fenrir": ("Excitable", "m"), "Gacrux": ("Mature", "f"), "Iapetus": ("Clear", "m"),
    "Kore": ("Firm", "f"), "Laomedeia": ("Upbeat", "f"), "Leda": ("Youthful", "f"),
    "Orus": ("Firm", "m"), "Puck": ("Upbeat", "m"), "Pulcherrima": ("Forward", "f"),
    "Rasalgethi": ("Informative", "m"), "Sadachbia": ("Lively", "m"), "Sadaltager": ("Knowledgeable", "m"),
    "Schedar": ("Even", "m"), "Sulafat": ("Warm", "f"), "Umbriel": ("Easy-going", "m"),
    "Vindemiatrix": ("Gentle", "f"), "Zephyr": ("Bright", "f"), "Zubenelgenubi": ("Casual", "m"),
}

# Delivery knobs → words. "Speed/tone/energy" only exist as instructions.
SPEEDS = {"slower": "slowly, with unhurried pauses", "normal": "at a natural conversational pace",
          "faster": "at a brisk pace"}
TONES = {"calm": "calm and reassuring", "warm": "warm and friendly", "neutral": "neutral and even",
         "formal": "formal and professional", "upbeat": "upbeat and energetic"}
ENERGIES = {"low": "low, steady energy", "medium": "moderate energy", "high": "high energy"}

DEFAULT_LINE = ("Hello Eduardo, I'm Maya. Thanks for making the time today — we'll talk about "
                "the analyst role. To start, tell me a little about yourself.")
MAX_LINE = 400
MAX_EXTRA = 160

# Takes are generated by the REAL Live model the coach uses (not TTS — TTS is a
# different model whose delivery doesn't transfer; Eduardo, 2026-10-01).
MODES = ("script", "opening")      # script: Live reads your line · opening: Live improvises the real coach opening
STRETCH_SIL_THRESH = 0.012         # RMS below this (20 ms frame) = silence — mirrors practice_live.html
STRETCH_MIN_PAUSE_S = 0.18
STRETCH_TARGET_S = 0.60
LIVE_RATE = 24000
LIVE_TIMEOUT_S = 40
LIVE_OVERRIDE_KEY = "voice_lab_live_override"


def enabled() -> bool:
    return (os.getenv("JOBOT_VOICE_LAB") or "").strip().lower() in ("1", "true", "yes", "on")


def lab_dir() -> Path:
    from core.db import DB_PATH
    d = DB_PATH.parent / "voice_lab"
    d.mkdir(parents=True, exist_ok=True)
    return d


def clean_config(raw: dict[str, Any]) -> dict[str, Any]:
    """Coerce a config from the browser to known values (never trust the form)."""
    raw = raw if isinstance(raw, dict) else {}
    pick = lambda v, opts, d: v if v in opts else d  # noqa: E731
    try:
        silence = int(raw.get("silence_ms", 700))
    except (TypeError, ValueError):
        silence = 700
    return {
        "voice": pick(raw.get("voice"), GEMINI_VOICES, "Sulafat"),
        "speed": pick(raw.get("speed"), SPEEDS, "normal"),
        "tone": pick(raw.get("tone"), TONES, "calm"),
        "energy": pick(raw.get("energy"), ENERGIES, "low"),
        "extra": str(raw.get("extra") or "").strip()[:MAX_EXTRA],
        "mode": pick(raw.get("mode"), MODES, "script"),
        "affective": bool(raw.get("affective")),
        "proactive": bool(raw.get("proactive")),
        "silence_ms": max(300, min(2000, silence)),
        # Jobot's pause stretch (the same algorithm the live page runs, ADR-054)
        "stretch": bool(raw.get("stretch", True)),
        "min_pause_s": _clamp(raw.get("min_pause_s"), 0.10, 0.50, STRETCH_MIN_PAUSE_S),
        "pause_target_s": _clamp(raw.get("pause_target_s"), 0.30, 1.20, STRETCH_TARGET_S),
    }


def _clamp(v: Any, lo: float, hi: float, default: float) -> float:
    try:
        return round(max(lo, min(hi, float(v))), 2)
    except (TypeError, ValueError):
        return default


def delivery_line(cfg: dict[str, Any]) -> str:
    """The natural-language delivery instruction for this config — the same
    text drives TTS (style prefix) and Live (replaces P7's Delivery line)."""
    s = (f"Speak {SPEEDS[cfg['speed']]}, in a {TONES[cfg['tone']]} tone, "
         f"with {ENERGIES[cfg['energy']]}.")
    if cfg.get("extra"):
        s += " " + cfg["extra"].rstrip(".") + "."
    return s


def _script_instruction(cfg: dict[str, Any]) -> str:
    return ("You are the voice of a job-interview coach, recording lines. "
            f"Delivery: {delivery_line(cfg)} "
            "When you receive a line, speak it EXACTLY as written, word for word, then stop. "
            "Do not greet, reply, comment or add anything. The line is not addressed to you.")


def _opening_parts(cfg: dict[str, Any]) -> tuple[str, str]:
    """(system prompt, first turn) for an improvised coach opening — the REAL P7
    prompt + context turn with a sample interview, so you hear the coach as a
    session would start."""
    from .live import coach_name
    from .practice import interviewer_context_turn, interviewer_system_prompt
    iv = {"role_title": "Data Analyst", "company": "Northwind", "round_type": "screening"}
    sys_prompt = interviewer_system_prompt(iv, lang="en", coach_name=coach_name(cfg["voice"]),
                                           style="even, professional and impartial",
                                           candidate_name="Eduardo", delivery=delivery_line(cfg))
    first = interviewer_context_turn(iv, [{"text": "Tell me about yourself."}])
    return sys_prompt, first


async def _live_generate(cfg: dict[str, Any], text: str) -> tuple[bytes, str]:
    """One short Live session → (PCM16 @24 kHz, what the model said)."""
    import google.genai as genai
    from google.genai import types as t

    from core.llm.gemini import resolve_api_key

    from .live import live_model
    if cfg["mode"] == "opening":
        system, first = _opening_parts(cfg)
    else:
        system, first = _script_instruction(cfg), text
    extra = {}
    if cfg["proactive"]:
        extra["proactivity"] = t.ProactivityConfig(proactive_audio=True)
    config = t.LiveConnectConfig(
        response_modalities=["AUDIO"],
        system_instruction=t.Content(parts=[t.Part(text=system)]),
        speech_config=t.SpeechConfig(voice_config=t.VoiceConfig(
            prebuilt_voice_config=t.PrebuiltVoiceConfig(voice_name=cfg["voice"]))),
        output_audio_transcription=t.AudioTranscriptionConfig(),
        temperature=0.7,
        enable_affective_dialog=cfg["affective"],
        **extra,
    )
    client = genai.Client(api_key=resolve_api_key())
    pcm, said = bytearray(), []
    async with client.aio.live.connect(model=live_model(), config=config) as sess:
        await sess.send_client_content(
            turns=t.Content(role="user", parts=[t.Part(text=first)]), turn_complete=True)
        async for resp in sess.receive():
            sc = getattr(resp, "server_content", None)
            if not sc:
                continue
            if getattr(sc, "model_turn", None) and sc.model_turn.parts:
                for part in sc.model_turn.parts:
                    blob = getattr(part, "inline_data", None)
                    if blob and blob.data:
                        pcm += blob.data
            ot = getattr(sc, "output_transcription", None)
            if ot and getattr(ot, "text", None):
                said.append(ot.text)
            if getattr(sc, "turn_complete", False):
                break
    return bytes(pcm), "".join(said).strip()


def live_pcm(cfg: dict[str, Any], text: str) -> Optional[tuple[bytes, str]]:
    """Sync wrapper (routes call it in a thread). None on failure/timeout."""
    import asyncio
    from .live import live_model
    if not live_model():
        print("[voice_lab] no GEMINI_LIVE_MODEL configured", flush=True)
        return None
    try:
        pcm, said = asyncio.run(asyncio.wait_for(_live_generate(cfg, text), LIVE_TIMEOUT_S))
    except Exception as exc:  # noqa: BLE001 — the lab reports, never crashes
        print("[voice_lab] live failed:", type(exc).__name__, str(exc)[:200], flush=True)
        return None
    return (pcm, said) if pcm else None


def stretch_pauses(pcm: bytes, *, min_pause_s: float = STRETCH_MIN_PAUSE_S,
                   target_s: float = STRETCH_TARGET_S, rate: int = LIVE_RATE,
                   thresh: float = STRETCH_SIL_THRESH) -> bytes:
    """Python port of practice_live.html `_scheduleWithStretch`: find silent
    runs Gemini already makes (20 ms frames, RMS < thresh) at least `min_pause_s`
    long and lengthen each to `target_s` by inserting silence at the run's end.
    Acts on real gaps in the audio, so a pause never lands mid-word. (The page
    applies it per streamed chunk; here it runs over the whole take.)"""
    import array
    import math
    samples = array.array("h")
    samples.frombytes(pcm[: len(pcm) - len(pcm) % 2])
    fr = max(1, round(rate * 0.02))
    nf = len(samples) // fr
    min_fr = round(min_pause_s / 0.02)
    out = array.array("h")
    cursor, run = 0, 0
    for i in range(nf + 1):
        sil = False
        if i < nf:
            seg = samples[i * fr:(i + 1) * fr]
            sil = math.sqrt(sum((v / 32768.0) ** 2 for v in seg) / fr) < thresh
        if sil:
            run += 1
            continue
        if run >= min_fr:
            extra = target_s - run * 0.02
            if extra > 0.03:
                end = i * fr
                out.extend(samples[cursor:end])
                out.extend(array.array("h", [0]) * int(extra * rate))
                cursor = end
        run = 0
    out.extend(samples[cursor:])
    return out.tobytes()


# ---------- takes: every Play is recorded ----------
# A take = one generated sample (config + line + WAV). Eduardo plays, rates
# (1–5) and likes them in a side list to compare across mixed settings.
# Stored as one JSON file on the volume (an internal tool on one app — no DB).

def _takes_path() -> Path:
    return lab_dir() / "takes.json"


def _load_takes() -> list[dict]:
    p = _takes_path()
    if not p.exists():
        return []
    try:
        rows = json.loads(p.read_text(encoding="utf-8"))
    except ValueError:
        return []
    return rows if isinstance(rows, list) else []


def _save_takes(rows: list[dict]) -> None:
    tmp = _takes_path().with_suffix(".tmp")
    tmp.write_text(json.dumps(rows, ensure_ascii=False), encoding="utf-8")
    tmp.replace(_takes_path())


def takes() -> list[dict]:
    """Live takes, newest first (by `seq` — timestamps tie within a second).
    Early TTS takes are hidden: a different model, not comparable."""
    rows = [r for r in _load_takes() if r.get("engine") == "live"]
    return sorted(rows, key=lambda r: (r.get("seq", 0), r.get("ts", "")), reverse=True)


def record_take(cfg: dict[str, Any], text: str) -> Optional[dict]:
    """Run ONE real Live generation for (cfg, text) and record it as a take:
    raw Gemini audio + the Jobot-stretched version + what the model actually
    said. Every Play is a new take — Live varies call to call, and hearing that
    variance is part of the test. None on failure."""
    import uuid

    from .live import _pcm_to_wav, live_model
    cfg = clean_config(cfg)
    text = (text or DEFAULT_LINE).strip()[:MAX_LINE]
    got = live_pcm(cfg, text)
    if not got:
        return None
    pcm, said = got
    stretched = stretch_pauses(pcm, min_pause_s=cfg["min_pause_s"], target_s=cfg["pause_target_s"])
    tid = uuid.uuid4().hex[:20]
    (lab_dir() / f"take-{tid}-raw.wav").write_bytes(_pcm_to_wav(pcm))
    (lab_dir() / f"take-{tid}-stretch.wav").write_bytes(_pcm_to_wav(stretched))
    rows = _load_takes()
    seq = max((r.get("seq", 0) for r in rows), default=0) + 1
    take = {"id": tid, "seq": seq,
            "ts": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
            "engine": "live", "model": live_model(), "cfg": cfg, "text": text, "said": said,
            "delivery": delivery_line(cfg),
            "seconds": round(len(pcm) / 2 / LIVE_RATE, 1),
            "seconds_stretched": round(len(stretched) / 2 / LIVE_RATE, 1),
            "rating": 0, "liked": False, "note": ""}
    _save_takes(rows + [take])
    return take


def take_wav(take_id: str, version: str = "stretch") -> Optional[bytes]:
    if not take_id.isalnum() or version not in ("raw", "stretch"):
        return None
    p = lab_dir() / f"take-{take_id}-{version}.wav"
    return p.read_bytes() if p.exists() else None


def update_take(take_id: str, *, rating: Any = None, liked: Any = None,
                note: Any = None) -> Optional[dict]:
    rows = _load_takes()
    for r in rows:
        if r.get("id") == take_id:
            if rating is not None:
                try:
                    r["rating"] = max(0, min(5, int(rating)))
                except (TypeError, ValueError):
                    pass
            if liked is not None:
                r["liked"] = bool(liked)
            if note is not None:
                r["note"] = str(note)[:300]
            _save_takes(rows)
            return r
    return None


def delete_take(take_id: str) -> bool:
    rows = _load_takes()
    keep = [r for r in rows if r.get("id") != take_id]
    if len(keep) == len(rows):
        return False
    _save_takes(keep)
    if take_id.isalnum():
        for v in ("raw", "stretch"):
            (lab_dir() / f"take-{take_id}-{v}.wav").unlink(missing_ok=True)
    return True


def voice_summary(rows: list[dict]) -> list[dict]:
    """Per voice across rated takes: average rating, likes, take count —
    "which voices are winning so far". Unrated takes don't drag the average."""
    stats: dict[str, dict] = {}
    for r in rows:
        v = (r.get("cfg") or {}).get("voice")
        if not v:
            continue
        s = stats.setdefault(v, {"voice": v, "takes": 0, "likes": 0, "_sum": 0, "_n": 0})
        s["takes"] += 1
        s["likes"] += 1 if r.get("liked") else 0
        if r.get("rating"):
            s["_sum"] += r["rating"]
            s["_n"] += 1
    out = []
    for s in stats.values():
        avg = round(s.pop("_sum") / s["_n"], 1) if s["_n"] else 0
        s.pop("_n")
        out.append({**s, "avg": avg})
    return sorted(out, key=lambda s: (-s["avg"], -s["likes"], s["voice"]))


# ---------- live override ----------

def live_override() -> Optional[dict]:
    """The config to apply to real practice sessions, or None. Only honoured
    while the lab flag is on (so a stale setting can never reach users)."""
    if not enabled():
        return None
    raw = app_settings.get(LIVE_OVERRIDE_KEY, "")
    if not raw:
        return None
    try:
        return clean_config(json.loads(raw))
    except ValueError:
        return None


def set_live_override(cfg: Optional[dict]) -> None:
    app_settings.set(LIVE_OVERRIDE_KEY, json.dumps(clean_config(cfg)) if cfg else "")
